### ISSUE TITLE
DNS not created correctly

### ISSUE THREAD

**Issue by aloonj** [d3atiq/netplan-networking#1]
I have used this successfully to set an IP & gateway, however, setting the DNS nameservers as per your readme, results in incorrect netplan format.

Correct:

```
nameservers:
  addresses: [192.168.0.1, 8.8.8.8]
```

**Comment by d3atiq** [comment]
Hi aloonj,
Would you kindly show me your playbook and the netplan yams file produced by this role?
Thanks!

**Comment by aloonj** [comment]
```
roles:
  - role: d3atiq.netplan_networking
    interfaces:
    - interface: ens192
      ipv4:
        configured: true
        address: 192.168.0.1/24
        gateway: 192.168.0.254
      dns:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4
```

```
 network:
  version: 2
  renderer: networkd
  ethernets:
    ens192:
      addresses:
       - 192.168.0.1/24
      gateway4: 192.168.0.254
      nameservers:
       - 8.8.8.8
       - 8.8.4.4
```

netplan try
Error in network definition //etc/netplan/ens192.yaml line 9 column 8: expected mapping

line 9  nameservers:

**Comment by aloonj** [comment]
Should it be
..
```
       dns:
         nameservers:
          - address: 8.8.8.8
	  - address: 8.8.4.4
```
